allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  '@swc/core': true
  '@tailwindcss/oxide': true
  '@temporalio/core-bridge': true
  esbuild: true
  prisma: true
  protobufjs: true
  sharp: true
